# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: /blog/:year/:month/:title/

# Setup
title: "Vishesh Handa's blog"
url: http://vhanda.in
baseurl: /
blogurl: /blog/

author:
  name: "Vishesh Handa"
  email: "me@vhanda.in"

twitter_username: vHanda
github_username: visheshhanda

plugins:
  - jekyll-postcss
  - jekyll-feed
