# Dependencies
#markdown:         redcarpet
#highlighter:      pygments

# Permalinks
permalink: /blog/:year/:month/:title/

# Setup
title:            "Vishesh Handa's blog"  
url:              http://vhanda.in
baseurl:          /
blogurl:          /blog/

author:
  name:           'Vishesh Handa'
  email:          'me@vhanda.in'

google_analytics: UA-23819011-1
