# Dependencies
#markdown:         redcarpet
#highlighter:      pygments

# Permalinks
permalink: /blog/:year/:month/:title/
#relative_permalinks: true

# Setup
title:            "Vishesh Handa's blog"  
#tagline:          'A Jekyll theme'
#description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://vhanda.in
baseurl:          /
blogurl:          /blog/
paginate_path:    /blog/page:num/

author:
  name:           'Vishesh Handa'
  url:            https://twitter.com/visheshhanda

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/vhanda

gems:             ['jekyll-paginate']
