baseURL = "http://vhanda.in"
disablePathToLower = true
languageCode = "en-us"
title = "Vishesh Handa's blog"
theme = "anatole"

[permalinks]
blog = "/blog/:year/:month/:title/"

[params]
title = "Vishesh Handa"
author = "Vishesh Handa"
description = "Haven't figured out a description"
profilePicture = "/images/profile.jpg"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/visheshhanda/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/vhanda"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/visheshhanda"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:me@vhanda.in"
